[package]
name = "schemify-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"

[[bin]]
name = "schemify"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
schemify = { path = "../schemify" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
